"""init

Revision ID: e68e62dd5f3a
Revises: 
Create Date: 2026-02-27 19:11:40.487718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68e62dd5f3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('raw_materials_loss_persentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('product_type_coef', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_name', sa.String(), nullable=False),
    sa.Column('workshop_type', sa.String(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prouct_type_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('articul', sa.Integer(), nullable=False),
    sa.Column('min_partner_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('base_material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_material_id'], ['material_types.id'], ),
    sa.ForeignKeyConstraint(['prouct_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('make_time', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_workshops')
    op.drop_table('products')
    op.drop_table('workshops')
    op.drop_table('product_types')
    op.drop_table('material_types')
    # ### end Alembic commands ###
